### ISSUE TITLE
Mod not found in Zen Mods page

### ISSUE THREAD

**Issue by JGoldz75** [litegral/zen-url-bar-tweaks#2]
Hi there,

Perhaps I'm doing something majorly wrong, but this morning I navigated to this mod on my phone and was able to locate it easily. I decided to download Zen just to download this Zen Mod, however, now I no longer see the mod as an option. Is something going on here? Is there a direct link I could use to access it? Does this mod disappear as an available option if another mod interferes with it? 

Thank you!

**Comment by litegral** [comment]
Hi! I don't know why Cheff (Zen maintainer) deleted the theme: https://github.com/zen-browser/theme-store/commit/7094ec38eefb95b60aa27bedbb3a0b4c4e5f62b0. I didn't get any notice from him.

But if you want to achieve the same functionality manually you can follow these 3 steps:
1. Open `about:profiles` and click `Open Folder` on the root directory of the profile that is currently in use.
2. Go to the `chrome` folder, then create userChrome.css
3. Paste this CSS inside
```css
@-moz-document url-prefix("chrome:") {
  
  /* === Base styles (always active) === */
  #urlbar-background {
    border: 2px solid transparent !important;
    border-radius: 8px !important;
    transition: box-shadow 0.3s ease-in-out !important;
  }

  /* === Optional: Hide container and permission icons === */
  /* Comment out the block below to disable this feature */
  
  #userContext-identity-icon,
  #userContext-indicator {
    display: none !important;
  }

  #identity-permission-box {
    opacity: 0;
    transition: opacity 0.2s ease-in-out !important;
  }

  #identity-box {
    margin-inline-end: 0 !important;
    max-width: 0 !important;
    padding: 0 !important;
    overflow: hidden !important;
  }

  #page-action-buttons {
    display: none !important;
  }
 
  /* === Optional: Show elements on hover === */
  /* Comment out the block below to disable this feature */
  
  #urlbar:hover #identity-permission-box {
    opacity: 1 !important;
  }

  #urlbar:hover #identity-box,
  #urlbar:focus-within #identity-box {
    max-width: unset !important;
    margin-inline-end: 4px !important;
  }

  #urlbar:hover #page-action-buttons,
  #urlbar:focus-within #page-action-buttons {
    display: flex !important;
  }
 

  /* === Optional: Center the URL in the address bar === */
  /* Comment out the block below to disable this feature */
  
  #urlbar-input-container {
    justify-content: center !important;
  }

  #urlbar-input {
    text-align: center !important;
  }
 

  /* === Optional: Apply colorful border === */
  /* Uncomment the block below to enable this feature */
  /*
  #urlbar-background {
    background-origin: border-box !important;
    background-clip: padding-box, border-box !important;
    background-image: linear-gradient(rgba(59, 59, 61, 0.8), rgba(59, 59, 61, 0.8)),
                      linear-gradient(90deg, #ff7e5f, #feb47b, #7bc6cc, #8583ed) !important;
  }
  */

  /* === Optional: Glow effect on focus === */
  /* Uncomment the block below to enable this feature */
  /*
  #urlbar-background {
    box-shadow: 0 0 8px rgba(137, 137, 186, 0.3) !important;
  }

  #urlbar[focused="true"] #urlbar-background {
    box-shadow: 0 0 12px rgba(99, 185, 255, 0.5) !important;
  }
  */

}
```
4. Then restart your zen
